// <auto-generated />
using System;
using HorseRacingPrediction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorseRacingPrediction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20260829033307_AddOwnerAliasAdministration")]
    partial class AddOwnerAliasAdministration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EventFlow.EntityFramework.EventStores.EventEntity", b =>
                {
                    b.Property<long>("GlobalSequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregateSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GlobalSequenceNumber");

                    b.HasIndex("AggregateId", "AggregateSequenceNumber")
                        .IsUnique();

                    b.ToTable("EventEntity");
                });

            modelBuilder.Entity("EventFlow.EntityFramework.SnapshotStores.SnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AggregateSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AggregateName", "AggregateId", "AggregateSequenceNumber")
                        .IsUnique();

                    b.ToTable("SnapshotEntity");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.HorseRaceHistoryReadModel", b =>
                {
                    b.Property<string>("HorseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HorseId");

                    b.ToTable("HorseRaceHistories");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.HorseReadModel", b =>
                {
                    b.Property<string>("HorseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SexCode")
                        .HasColumnType("TEXT");

                    b.HasKey("HorseId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.HorseWeightHistoryReadModel", b =>
                {
                    b.Property<string>("HorseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HorseId");

                    b.ToTable("HorseWeightHistories");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.JockeyRaceHistoryReadModel", b =>
                {
                    b.Property<string>("JockeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JockeyId");

                    b.ToTable("JockeyRaceHistories");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.JockeyReadModel", b =>
                {
                    b.Property<string>("JockeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffiliationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JockeyId");

                    b.ToTable("Jockeys");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.MemoBySubjectReadModel", b =>
                {
                    b.Property<string>("SubjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Memos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectKey");

                    b.ToTable("MemoSubjects");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.OwnerAliasMappingReadModel", b =>
                {
                    b.Property<string>("NormalizedAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NormalizedAlias");

                    b.HasIndex("OwnerId");

                    b.ToTable("OwnerAliasMappings");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.OwnerMergeAuditReadModel", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetOwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("TargetOwnerId", "CreatedAt");

                    b.ToTable("OwnerMergeAudits");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.PredictionComparisonViewReadModel", b =>
                {
                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryIndexes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultDeclaredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketStates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningHorseName")
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("PredictionComparisons");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.PredictionTicketReadModel", b =>
                {
                    b.Property<string>("PredictionTicketId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evaluations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PredictedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictorType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryComment")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("PredictionTicketId");

                    b.ToTable("PredictionTickets");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.RacePredictionContextReadModel", b =>
                {
                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectionCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeCode")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RacecourseCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurfaceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackConditionObservations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherObservations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("RacePredictionContexts");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.RaceResultViewReadModel", b =>
                {
                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryIndexes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutResult")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RacecourseCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultDeclaredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StewardReportText")
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningHorseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningHorseName")
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.RaceSummaryReadModel", b =>
                {
                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RacecourseCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResultDeclaredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinningHorseName")
                        .HasColumnType("TEXT");

                    b.HasKey("RaceId");

                    b.ToTable("RaceSummaries");
                });

            modelBuilder.Entity("HorseRacingPrediction.Application.Queries.ReadModels.TrainerReadModel", b =>
                {
                    b.Property<string>("TrainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffiliationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");
                });
#pragma warning restore 612, 618
        }
    }
}
