<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HorseRacingPrediction.Collector\HorseRacingPrediction.Collector.csproj" />
    <ProjectReference Include="..\HorseRacingPrediction.ApiClient\HorseRacingPrediction.ApiClient.csproj" />
    <ProjectReference Include="..\HorseRacingPrediction.Scraping\HorseRacingPrediction.Scraping.csproj" />
  </ItemGroup>

</Project>