using Refit;

namespace HorseRacingPrediction.ApiClient.Collection;

internal sealed class CollectionApiFacade(ICollectionTransport transport) : ICollectionApi
{
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.AcquireCollectionTaskResponse>> AcquireCollectionTaskAsync(global::HorseRacingPrediction.Contracts.Collection.AcquireCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.AcquireCollectionTaskAsync(request.Id, request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.AcquireNextExecutionResponse>> AcquireNextExecutionAsync(global::HorseRacingPrediction.Contracts.Collection.AcquireNextExecutionRequest request, CancellationToken cancellationToken = default) => transport.AcquireNextExecutionAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ApplyRaceDetailMigrationResponse>> ApplyRaceDetailMigrationAsync(CancellationToken cancellationToken = default) => transport.ApplyRaceDetailMigrationAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ApplyRaceEntryOwnerMigrationResponse>> ApplyRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.ApplyRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<IApiResponse> CancelCollectionTaskAsync(global::HorseRacingPrediction.Contracts.Collection.CancelCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.CancelCollectionTaskAsync(request.Id, request, cancellationToken);
    public Task<IApiResponse> CompleteCollectionTaskAttemptAsync(global::HorseRacingPrediction.Contracts.Collection.CompleteCollectionTaskAttemptRequest request, CancellationToken cancellationToken = default) => transport.CompleteCollectionTaskAttemptAsync(request.Id, request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateBackfillBatchResponse>> CreateBackfillBatchAsync(global::HorseRacingPrediction.Contracts.Collection.CreateBackfillBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateBackfillBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRecoveryBatchResponse>> CreateCollectionRecoveryBatchAsync(global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRecoveryBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionRecoveryBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRevisionResponse>> CreateCollectionRevisionAsync(global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRevisionRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionRevisionAsync(request.Definition, request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskBatchResponse>> CreateCollectionTaskBatchAsync(global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionTaskBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskResponse>> CreateCollectionTaskAsync(global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionTaskAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateKnownRecoveryBatchResponse>> CreateKnownRecoveryBatchAsync(CancellationToken cancellationToken = default) => transport.CreateKnownRecoveryBatchAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateRaceEntryOwnerRepairBatchResponse>> CreateRaceEntryOwnerRepairBatchAsync(global::HorseRacingPrediction.Contracts.Collection.CreateRaceEntryOwnerRepairBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateRaceEntryOwnerRepairBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateRecollectionBatchResponse>> CreateRecollectionBatchAsync(global::HorseRacingPrediction.Contracts.Collection.CreateRecollectionBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateRecollectionBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetBackfillBatchResponse>> GetBackfillBatchAsync(global::HorseRacingPrediction.Contracts.Collection.GetBackfillBatchRequest request, CancellationToken cancellationToken = default) => transport.GetBackfillBatchAsync(request.Id, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionDashboardResponse>> GetCollectionDashboardAsync(CancellationToken cancellationToken = default) => transport.GetCollectionDashboardAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionMonitoringFindingsResponse>> GetCollectionMonitoringFindingsAsync(CancellationToken cancellationToken = default) => transport.GetCollectionMonitoringFindingsAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionRuntimeStatusResponse>> GetCollectionRuntimeStatusAsync(CancellationToken cancellationToken = default) => transport.GetCollectionRuntimeStatusAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionPipelineResponse>> GetCollectionPipelineAsync(CancellationToken cancellationToken = default) => transport.GetCollectionPipelineAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionProgressResponse>> GetCollectionProgressAsync(CancellationToken cancellationToken = default) => transport.GetCollectionProgressAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceDetailResponse>> GetCollectionResourceDetailAsync(global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceDetailRequest request, CancellationToken cancellationToken = default) => transport.GetCollectionResourceDetailAsync(request.Type, request.Provider, request.ResourceId, request.Definition, request.HistoryPage, request.RequestHistoryPage, request.TaskHistoryPage, request.AttemptHistoryPage, request.HistoryPageSize, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceStateResponse>> GetCollectionResourceStateAsync(global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceStateRequest request, CancellationToken cancellationToken = default) => transport.GetCollectionResourceStateAsync(request.Type, request.Provider, request.ResourceId, request.DefinitionId, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetExecutionBatchResponse>> GetExecutionBatchAsync(global::HorseRacingPrediction.Contracts.Collection.GetExecutionBatchRequest request, CancellationToken cancellationToken = default) => transport.GetExecutionBatchAsync(request.Id, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetFailureNotificationGroupResponse>> GetFailureNotificationGroupAsync(global::HorseRacingPrediction.Contracts.Collection.GetFailureNotificationGroupRequest request, CancellationToken cancellationToken = default) => transport.GetFailureNotificationGroupAsync(request.GroupKey, request.Search, request.Page, request.PageSize, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetKnownRecoveryPreviewResponse>> GetKnownRecoveryPreviewAsync(CancellationToken cancellationToken = default) => transport.GetKnownRecoveryPreviewAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetOwnerIdentityMigrationPreviewResponse>> GetOwnerIdentityMigrationPreviewAsync(CancellationToken cancellationToken = default) => transport.GetOwnerIdentityMigrationPreviewAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRaceCollectionReadinessResponse>> GetRaceCollectionReadinessAsync(global::HorseRacingPrediction.Contracts.Collection.GetRaceCollectionReadinessRequest request, CancellationToken cancellationToken = default) => transport.GetRaceCollectionReadinessAsync(request.RaceId, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRaceEntryOwnerMigrationResponse>> GetRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.GetRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRevisionRecollectionProgressResponse>> GetRevisionRecollectionProgressAsync(global::HorseRacingPrediction.Contracts.Collection.GetRevisionRecollectionProgressRequest request, CancellationToken cancellationToken = default) => transport.GetRevisionRecollectionProgressAsync(request.Definition, request.Revision, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetTaskViewCountsResponse>> GetTaskViewCountsAsync(CancellationToken cancellationToken = default) => transport.GetTaskViewCountsAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.HeartbeatCollectionTaskLeaseResponse>> HeartbeatCollectionTaskLeaseAsync(global::HorseRacingPrediction.Contracts.Collection.HeartbeatCollectionTaskLeaseRequest request, CancellationToken cancellationToken = default) => transport.HeartbeatCollectionTaskLeaseAsync(request.Id, request.LeaseId, request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListBackfillBatchesResponse>> ListBackfillBatchesAsync(CancellationToken cancellationToken = default) => transport.ListBackfillBatchesAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListCollectionTasksResponse>> ListCollectionTasksAsync(global::HorseRacingPrediction.Contracts.Collection.ListCollectionTasksRequest request, CancellationToken cancellationToken = default) => transport.ListCollectionTasksAsync(request.Status, request.Limit, request.Statuses, request.ResourceType, request.Provider, request.DefinitionId, request.Lane, request.Search, request.ErrorSearch, request.CreatedFrom, request.CreatedTo, request.ActionableOnly, request.LatestOnly, request.Page, request.PageSize, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationGroupsResponse>> ListFailureNotificationGroupsAsync(global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationGroupsRequest request, CancellationToken cancellationToken = default) => transport.ListFailureNotificationGroupsAsync(request.Limit, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationsResponse>> ListFailureNotificationsAsync(global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationsRequest request, CancellationToken cancellationToken = default) => transport.ListFailureNotificationsAsync(request.View, request.Published, request.DeliveryState, request.Limit, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListRaceEntryOwnerRepairCandidatesResponse>> ListRaceEntryOwnerRepairCandidatesAsync(global::HorseRacingPrediction.Contracts.Collection.ListRaceEntryOwnerRepairCandidatesRequest request, CancellationToken cancellationToken = default) => transport.ListRaceEntryOwnerRepairCandidatesAsync(request.Date, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewCollectionTaskBatchResponse>> PreviewCollectionTaskBatchAsync(global::HorseRacingPrediction.Contracts.Collection.PreviewCollectionTaskBatchRequest request, CancellationToken cancellationToken = default) => transport.PreviewCollectionTaskBatchAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRaceDetailMigrationResponse>> PreviewRaceDetailMigrationAsync(CancellationToken cancellationToken = default) => transport.PreviewRaceDetailMigrationAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRaceEntryOwnerMigrationResponse>> PreviewRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.PreviewRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRacePeriodRecollectionResponse>> PreviewRacePeriodRecollectionAsync(global::HorseRacingPrediction.Contracts.Collection.PreviewRacePeriodRecollectionRequest request, CancellationToken cancellationToken = default) => transport.PreviewRacePeriodRecollectionAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRevisionImpactResponse>> PreviewRevisionImpactAsync(global::HorseRacingPrediction.Contracts.Collection.PreviewRevisionImpactRequest request, CancellationToken cancellationToken = default) => transport.PreviewRevisionImpactAsync(request, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.RecoverBackfillHolesResponse>> RecoverBackfillHolesAsync(global::HorseRacingPrediction.Contracts.Collection.RecoverBackfillHolesRequest request, CancellationToken cancellationToken = default) => transport.RecoverBackfillHolesAsync(request.Id, cancellationToken);
    public Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.SearchCollectionStatesResponse>> SearchCollectionStatesAsync(global::HorseRacingPrediction.Contracts.Collection.SearchCollectionStatesRequest request, CancellationToken cancellationToken = default) => transport.SearchCollectionStatesAsync(request.Statuses, request.ResourceType, request.Provider, request.DefinitionId, request.Search, request.Page, request.PageSize, cancellationToken);
    public Task<IApiResponse> SetCollectionPipelineAsync(global::HorseRacingPrediction.Contracts.Collection.SetCollectionPipelineRequest request, CancellationToken cancellationToken = default) => transport.SetCollectionPipelineAsync(request, cancellationToken);
    public Task<IApiResponse> TransitionCollectionExecutionAsync(global::HorseRacingPrediction.Contracts.Collection.TransitionCollectionExecutionRequest request, CancellationToken cancellationToken = default) => transport.TransitionCollectionExecutionAsync(request.Id, request, cancellationToken);
}
