using HorseRacingPrediction.Contracts.Collection;
using Refit;

namespace HorseRacingPrediction.ApiClient.Collection;

internal sealed class CollectionApiFacade(ICollectionTransport transport) : ICollectionApi
{
    public Task<ApiResponse<AcquireCollectionTaskResponse>> AcquireCollectionTaskAsync(AcquireCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.AcquireCollectionTaskAsync(request.Id, request, cancellationToken);
    public Task<ApiResponse<AcquireNextExecutionResponse>> AcquireNextExecutionAsync(AcquireNextExecutionRequest request, CancellationToken cancellationToken = default) => transport.AcquireNextExecutionAsync(request, cancellationToken);
    public Task<ApiResponse<ApplyRaceDetailMigrationResponse>> ApplyRaceDetailMigrationAsync(CancellationToken cancellationToken = default) => transport.ApplyRaceDetailMigrationAsync(cancellationToken);
    public Task<ApiResponse<ApplyRaceEntryOwnerMigrationResponse>> ApplyRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.ApplyRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<IApiResponse> CancelCollectionTaskAsync(CancelCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.CancelCollectionTaskAsync(request.Id, request, cancellationToken);
    public Task<IApiResponse> CompleteCollectionTaskAttemptAsync(CompleteCollectionTaskAttemptRequest request, CancellationToken cancellationToken = default) => transport.CompleteCollectionTaskAttemptAsync(request.Id, request, cancellationToken);
    public Task<ApiResponse<CreateBackfillBatchResponse>> CreateBackfillBatchAsync(CreateBackfillBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateBackfillBatchAsync(request, cancellationToken);
    public Task<ApiResponse<CreateCollectionRecoveryBatchResponse>> CreateCollectionRecoveryBatchAsync(CreateCollectionRecoveryBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionRecoveryBatchAsync(request, cancellationToken);
    public Task<ApiResponse<CreateCollectionRevisionResponse>> CreateCollectionRevisionAsync(CreateCollectionRevisionRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionRevisionAsync(request.Definition, request, cancellationToken);
    public Task<ApiResponse<CreateCollectionTaskBatchResponse>> CreateCollectionTaskBatchAsync(CreateCollectionTaskBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionTaskBatchAsync(request, cancellationToken);
    public Task<ApiResponse<CreateCollectionTaskResponse>> CreateCollectionTaskAsync(CreateCollectionTaskRequest request, CancellationToken cancellationToken = default) => transport.CreateCollectionTaskAsync(request, cancellationToken);
    public Task<ApiResponse<CreateKnownRecoveryBatchResponse>> CreateKnownRecoveryBatchAsync(CancellationToken cancellationToken = default) => transport.CreateKnownRecoveryBatchAsync(cancellationToken);
    public Task<ApiResponse<CreateRaceEntryOwnerRepairBatchResponse>> CreateRaceEntryOwnerRepairBatchAsync(CreateRaceEntryOwnerRepairBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateRaceEntryOwnerRepairBatchAsync(request, cancellationToken);
    public Task<ApiResponse<CreateRecollectionBatchResponse>> CreateRecollectionBatchAsync(CreateRecollectionBatchRequest request, CancellationToken cancellationToken = default) => transport.CreateRecollectionBatchAsync(request, cancellationToken);
    public Task<ApiResponse<GetBackfillBatchResponse>> GetBackfillBatchAsync(GetBackfillBatchRequest request, CancellationToken cancellationToken = default) => transport.GetBackfillBatchAsync(request.Id, cancellationToken);
    public Task<ApiResponse<GetCollectionDashboardResponse>> GetCollectionDashboardAsync(CancellationToken cancellationToken = default) => transport.GetCollectionDashboardAsync(cancellationToken);
    public Task<ApiResponse<GetCollectionMonitoringFindingsResponse>> GetCollectionMonitoringFindingsAsync(CancellationToken cancellationToken = default) => transport.GetCollectionMonitoringFindingsAsync(cancellationToken);
    public Task<ApiResponse<GetCollectionPipelineResponse>> GetCollectionPipelineAsync(CancellationToken cancellationToken = default) => transport.GetCollectionPipelineAsync(cancellationToken);
    public Task<ApiResponse<GetCollectionProgressResponse>> GetCollectionProgressAsync(CancellationToken cancellationToken = default) => transport.GetCollectionProgressAsync(cancellationToken);
    public Task<ApiResponse<GetCollectionResourceDetailResponse>> GetCollectionResourceDetailAsync(GetCollectionResourceDetailRequest request, CancellationToken cancellationToken = default) => transport.GetCollectionResourceDetailAsync(request.Type, request.Provider, request.ResourceId, request.Definition, request.HistoryPage, request.RequestHistoryPage, request.TaskHistoryPage, request.AttemptHistoryPage, request.HistoryPageSize, cancellationToken);
    public Task<ApiResponse<GetCollectionResourceStateResponse>> GetCollectionResourceStateAsync(GetCollectionResourceStateRequest request, CancellationToken cancellationToken = default) => transport.GetCollectionResourceStateAsync(request.Type, request.Provider, request.ResourceId, request.DefinitionId, cancellationToken);
    public Task<ApiResponse<GetExecutionBatchResponse>> GetExecutionBatchAsync(GetExecutionBatchRequest request, CancellationToken cancellationToken = default) => transport.GetExecutionBatchAsync(request.Id, cancellationToken);
    public Task<ApiResponse<GetFailureNotificationGroupResponse>> GetFailureNotificationGroupAsync(GetFailureNotificationGroupRequest request, CancellationToken cancellationToken = default) => transport.GetFailureNotificationGroupAsync(request.GroupKey, request.Search, request.Page, request.PageSize, cancellationToken);
    public Task<ApiResponse<GetKnownRecoveryPreviewResponse>> GetKnownRecoveryPreviewAsync(CancellationToken cancellationToken = default) => transport.GetKnownRecoveryPreviewAsync(cancellationToken);
    public Task<ApiResponse<GetOwnerIdentityMigrationPreviewResponse>> GetOwnerIdentityMigrationPreviewAsync(CancellationToken cancellationToken = default) => transport.GetOwnerIdentityMigrationPreviewAsync(cancellationToken);
    public Task<ApiResponse<GetRaceCollectionReadinessResponse>> GetRaceCollectionReadinessAsync(GetRaceCollectionReadinessRequest request, CancellationToken cancellationToken = default) => transport.GetRaceCollectionReadinessAsync(request.RaceId, cancellationToken);
    public Task<ApiResponse<GetRaceEntryOwnerMigrationResponse>> GetRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.GetRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<ApiResponse<GetRevisionRecollectionProgressResponse>> GetRevisionRecollectionProgressAsync(GetRevisionRecollectionProgressRequest request, CancellationToken cancellationToken = default) => transport.GetRevisionRecollectionProgressAsync(request.Definition, request.Revision, cancellationToken);
    public Task<ApiResponse<GetTaskViewCountsResponse>> GetTaskViewCountsAsync(CancellationToken cancellationToken = default) => transport.GetTaskViewCountsAsync(cancellationToken);
    public Task<ApiResponse<HeartbeatCollectionTaskLeaseResponse>> HeartbeatCollectionTaskLeaseAsync(HeartbeatCollectionTaskLeaseRequest request, CancellationToken cancellationToken = default) => transport.HeartbeatCollectionTaskLeaseAsync(request.Id, request.LeaseId, request, cancellationToken);
    public Task<ApiResponse<ListBackfillBatchesResponse>> ListBackfillBatchesAsync(CancellationToken cancellationToken = default) => transport.ListBackfillBatchesAsync(cancellationToken);
    public Task<ApiResponse<ListCollectionTasksResponse>> ListCollectionTasksAsync(ListCollectionTasksRequest request, CancellationToken cancellationToken = default) => transport.ListCollectionTasksAsync(request.Status, request.Limit, request.Statuses, request.ResourceType, request.Provider, request.DefinitionId, request.Lane, request.Search, request.ErrorSearch, request.CreatedFrom, request.CreatedTo, request.ActionableOnly, request.LatestOnly, request.Page, request.PageSize, cancellationToken);
    public Task<ApiResponse<ListFailureNotificationGroupsResponse>> ListFailureNotificationGroupsAsync(ListFailureNotificationGroupsRequest request, CancellationToken cancellationToken = default) => transport.ListFailureNotificationGroupsAsync(request.Limit, cancellationToken);
    public Task<ApiResponse<ListFailureNotificationsResponse>> ListFailureNotificationsAsync(ListFailureNotificationsRequest request, CancellationToken cancellationToken = default) => transport.ListFailureNotificationsAsync(request.View, request.Published, request.DeliveryState, request.Limit, cancellationToken);
    public Task<ApiResponse<ListRaceEntryOwnerRepairCandidatesResponse>> ListRaceEntryOwnerRepairCandidatesAsync(ListRaceEntryOwnerRepairCandidatesRequest request, CancellationToken cancellationToken = default) => transport.ListRaceEntryOwnerRepairCandidatesAsync(request.Date, cancellationToken);
    public Task<ApiResponse<PreviewCollectionTaskBatchResponse>> PreviewCollectionTaskBatchAsync(PreviewCollectionTaskBatchRequest request, CancellationToken cancellationToken = default) => transport.PreviewCollectionTaskBatchAsync(request, cancellationToken);
    public Task<ApiResponse<PreviewRaceDetailMigrationResponse>> PreviewRaceDetailMigrationAsync(CancellationToken cancellationToken = default) => transport.PreviewRaceDetailMigrationAsync(cancellationToken);
    public Task<ApiResponse<PreviewRaceEntryOwnerMigrationResponse>> PreviewRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken = default) => transport.PreviewRaceEntryOwnerMigrationAsync(cancellationToken);
    public Task<ApiResponse<PreviewRacePeriodRecollectionResponse>> PreviewRacePeriodRecollectionAsync(PreviewRacePeriodRecollectionRequest request, CancellationToken cancellationToken = default) => transport.PreviewRacePeriodRecollectionAsync(request, cancellationToken);
    public Task<ApiResponse<PreviewRevisionImpactResponse>> PreviewRevisionImpactAsync(PreviewRevisionImpactRequest request, CancellationToken cancellationToken = default) => transport.PreviewRevisionImpactAsync(request, cancellationToken);
    public Task<ApiResponse<RecoverBackfillHolesResponse>> RecoverBackfillHolesAsync(RecoverBackfillHolesRequest request, CancellationToken cancellationToken = default) => transport.RecoverBackfillHolesAsync(request.Id, cancellationToken);
    public Task<ApiResponse<SearchCollectionStatesResponse>> SearchCollectionStatesAsync(SearchCollectionStatesRequest request, CancellationToken cancellationToken = default) => transport.SearchCollectionStatesAsync(request.Statuses, request.ResourceType, request.Provider, request.DefinitionId, request.Search, request.Page, request.PageSize, cancellationToken);
    public Task<IApiResponse> SetCollectionPipelineAsync(SetCollectionPipelineRequest request, CancellationToken cancellationToken = default) => transport.SetCollectionPipelineAsync(request, cancellationToken);
    public Task<IApiResponse> TransitionCollectionExecutionAsync(TransitionCollectionExecutionRequest request, CancellationToken cancellationToken = default) => transport.TransitionCollectionExecutionAsync(request.Id, request, cancellationToken);
}
