using Refit;
using HorseRacingPrediction.Contracts.Collection;

namespace HorseRacingPrediction.ApiClient.Collection;

internal interface ICollectionTransport
{
    [Post("/api/v2/internal/collection/tasks/{id}/leases")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.AcquireCollectionTaskResponse>> AcquireCollectionTaskAsync([AliasAs("id")] Guid id, [Body] global::HorseRacingPrediction.Contracts.Collection.AcquireCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/internal/collection/execution-leases")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.AcquireNextExecutionResponse>> AcquireNextExecutionAsync([Body] global::HorseRacingPrediction.Contracts.Collection.AcquireNextExecutionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migrations/race-detail")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ApplyRaceDetailMigrationResponse>> ApplyRaceDetailMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migrations/race-entry-owner-repair")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ApplyRaceEntryOwnerMigrationResponse>> ApplyRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Patch("/api/v2/admin/collection/tasks/{taskId}")] Task<IApiResponse> CancelCollectionTaskAsync([AliasAs("taskId")] Guid taskId, [Body] global::HorseRacingPrediction.Contracts.Collection.CancelCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/internal/collection/tasks/{id}/attempts")] Task<IApiResponse> CompleteCollectionTaskAttemptAsync([AliasAs("id")] Guid id, [Body] global::HorseRacingPrediction.Contracts.Collection.CompleteCollectionTaskAttemptRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/backfill-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateBackfillBatchResponse>> CreateBackfillBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateBackfillBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recovery-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRecoveryBatchResponse>> CreateCollectionRecoveryBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRecoveryBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/definitions/{definition}/revisions")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRevisionResponse>> CreateCollectionRevisionAsync([AliasAs("definition")] string definition, [Body] global::HorseRacingPrediction.Contracts.Collection.CreateCollectionRevisionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/task-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskBatchResponse>> CreateCollectionTaskBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/tasks")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskResponse>> CreateCollectionTaskAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/known-recovery-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateKnownRecoveryBatchResponse>> CreateKnownRecoveryBatchAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/race-entry-owner-repair-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateRaceEntryOwnerRepairBatchResponse>> CreateRaceEntryOwnerRepairBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateRaceEntryOwnerRepairBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recollection-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.CreateRecollectionBatchResponse>> CreateRecollectionBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.CreateRecollectionBatchRequest request, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/backfill-batches/{id}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetBackfillBatchResponse>> GetBackfillBatchAsync([AliasAs("id")] string id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/dashboard")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionDashboardResponse>> GetCollectionDashboardAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/monitoring-findings")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionMonitoringFindingsResponse>> GetCollectionMonitoringFindingsAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/runtime-status")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionRuntimeStatusResponse>> GetCollectionRuntimeStatusAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/pipeline-state")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionPipelineResponse>> GetCollectionPipelineAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/progress")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionProgressResponse>> GetCollectionProgressAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/resources/{type}/{provider}/{resourceId}/definitions/{definition}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceDetailResponse>> GetCollectionResourceDetailAsync([AliasAs("type")] CollectionResourceType type, [AliasAs("provider")] string provider, [AliasAs("resourceId")] string resourceId, [AliasAs("definition")] string definition, [AliasAs("historyPage")] int? historyPage, [AliasAs("requestHistoryPage")] int? requestHistoryPage, [AliasAs("taskHistoryPage")] int? taskHistoryPage, [AliasAs("attemptHistoryPage")] int? attemptHistoryPage, [AliasAs("historyPageSize")] int? historyPageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/resources/{type}/{provider}/{resourceId}/definitions/{definition}/state")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetCollectionResourceStateResponse>> GetCollectionResourceStateAsync([AliasAs("type")] CollectionResourceType type, [AliasAs("provider")] string provider, [AliasAs("resourceId")] string resourceId, [AliasAs("definition")] string definition, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/execution-batches/{id}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetExecutionBatchResponse>> GetExecutionBatchAsync([AliasAs("id")] Guid id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notification-groups/{groupKey}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetFailureNotificationGroupResponse>> GetFailureNotificationGroupAsync([AliasAs("groupKey")] string groupKey, [AliasAs("search")] string? search, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/recovery-previews/known")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetKnownRecoveryPreviewResponse>> GetKnownRecoveryPreviewAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/migration-previews/owner-identity")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetOwnerIdentityMigrationPreviewResponse>> GetOwnerIdentityMigrationPreviewAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/races/{raceId}/readiness")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRaceCollectionReadinessResponse>> GetRaceCollectionReadinessAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/migrations/race-entry-owner-repair")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRaceEntryOwnerMigrationResponse>> GetRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/recollection-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetRevisionRecollectionProgressResponse>> GetRevisionRecollectionProgressAsync([AliasAs("definition")] string definition, [AliasAs("revision")] int revision, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/task-view-counts")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.GetTaskViewCountsResponse>> GetTaskViewCountsAsync(CancellationToken cancellationToken);
    [Patch("/api/v2/internal/collection/tasks/{id}/leases/{leaseId}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.HeartbeatCollectionTaskLeaseResponse>> HeartbeatCollectionTaskLeaseAsync([AliasAs("id")] Guid id, [AliasAs("leaseId")] string leaseId, [Body] global::HorseRacingPrediction.Contracts.Collection.HeartbeatCollectionTaskLeaseRequest request, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/backfill-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListBackfillBatchesResponse>> ListBackfillBatchesAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/tasks")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListCollectionTasksResponse>> ListCollectionTasksAsync([AliasAs("status")] global::HorseRacingPrediction.Contracts.Collection.CollectionTaskStatus? status, [AliasAs("limit")] int? limit, [AliasAs("statuses")] string? statuses, [AliasAs("resourceType")] global::HorseRacingPrediction.Contracts.Collection.CollectionResourceType? resourceType, [AliasAs("provider")] string? provider, [AliasAs("definitionId")] string? definitionId, [AliasAs("lane")] global::HorseRacingPrediction.Contracts.Collection.CollectionLane? lane, [AliasAs("search")] string? search, [AliasAs("errorSearch")] string? errorSearch, [AliasAs("createdFrom")] DateTimeOffset? createdFrom, [AliasAs("createdTo")] DateTimeOffset? createdTo, [AliasAs("actionableOnly")] bool? actionableOnly, [AliasAs("latestOnly")] bool? latestOnly, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notification-groups")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationGroupsResponse>> ListFailureNotificationGroupsAsync([AliasAs("limit")] int? limit, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notifications")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListFailureNotificationsResponse>> ListFailureNotificationsAsync([AliasAs("view")] string? view, [AliasAs("published")] bool? published, [AliasAs("deliveryState")] string? deliveryState, [AliasAs("limit")] int? limit, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/race-entry-owner-repair-candidates")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.ListRaceEntryOwnerRepairCandidatesResponse>> ListRaceEntryOwnerRepairCandidatesAsync([AliasAs("date")] DateOnly date, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/task-batch-previews")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewCollectionTaskBatchResponse>> PreviewCollectionTaskBatchAsync([Body] global::HorseRacingPrediction.Contracts.Collection.PreviewCollectionTaskBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migration-previews/race-detail")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRaceDetailMigrationResponse>> PreviewRaceDetailMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migration-previews/race-entry-owner-repair")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRaceEntryOwnerMigrationResponse>> PreviewRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recollection-previews")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRacePeriodRecollectionResponse>> PreviewRacePeriodRecollectionAsync([Body] global::HorseRacingPrediction.Contracts.Collection.PreviewRacePeriodRecollectionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/revision-impact-previews")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.PreviewRevisionImpactResponse>> PreviewRevisionImpactAsync([Body] global::HorseRacingPrediction.Contracts.Collection.PreviewRevisionImpactRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/backfill-batches/{id}/recovery-batches")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.RecoverBackfillHolesResponse>> RecoverBackfillHolesAsync([AliasAs("id")] string id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/states")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Collection.SearchCollectionStatesResponse>> SearchCollectionStatesAsync([AliasAs("statuses")] string? statuses, [AliasAs("resourceType")] global::HorseRacingPrediction.Contracts.Collection.CollectionResourceType? resourceType, [AliasAs("provider")] string? provider, [AliasAs("definitionId")] string? definitionId, [AliasAs("search")] string? search, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Put("/api/v2/admin/collection/pipeline")] Task<IApiResponse> SetCollectionPipelineAsync([Body] global::HorseRacingPrediction.Contracts.Collection.SetCollectionPipelineRequest request, CancellationToken cancellationToken);
    [Patch("/api/v2/internal/collection/execution-batches/{id}")] Task<IApiResponse> TransitionCollectionExecutionAsync([AliasAs("id")] Guid id, [Body] global::HorseRacingPrediction.Contracts.Collection.TransitionCollectionExecutionRequest request, CancellationToken cancellationToken);
}
