using HorseRacingPrediction.Contracts.Collection;
using Refit;

namespace HorseRacingPrediction.ApiClient.Collection;

internal interface ICollectionTransport
{
    [Post("/api/v2/internal/collection/tasks/{id}/leases")] Task<ApiResponse<AcquireCollectionTaskResponse>> AcquireCollectionTaskAsync([AliasAs("id")] Guid id, [Body] AcquireCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/internal/collection/execution-leases")] Task<ApiResponse<AcquireNextExecutionResponse>> AcquireNextExecutionAsync([Body] AcquireNextExecutionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migrations/race-detail")] Task<ApiResponse<ApplyRaceDetailMigrationResponse>> ApplyRaceDetailMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migrations/race-entry-owner-repair")] Task<ApiResponse<ApplyRaceEntryOwnerMigrationResponse>> ApplyRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Patch("/api/v2/admin/collection/tasks/{taskId}")] Task<IApiResponse> CancelCollectionTaskAsync([AliasAs("taskId")] Guid taskId, [Body] CancelCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/internal/collection/tasks/{id}/attempts")] Task<IApiResponse> CompleteCollectionTaskAttemptAsync([AliasAs("id")] Guid id, [Body] CompleteCollectionTaskAttemptRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/backfill-batches")] Task<ApiResponse<CreateBackfillBatchResponse>> CreateBackfillBatchAsync([Body] CreateBackfillBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recovery-batches")] Task<ApiResponse<CreateCollectionRecoveryBatchResponse>> CreateCollectionRecoveryBatchAsync([Body] CreateCollectionRecoveryBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/definitions/{definition}/revisions")] Task<ApiResponse<CreateCollectionRevisionResponse>> CreateCollectionRevisionAsync([AliasAs("definition")] string definition, [Body] CreateCollectionRevisionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/task-batches")] Task<ApiResponse<CreateCollectionTaskBatchResponse>> CreateCollectionTaskBatchAsync([Body] CreateCollectionTaskBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/tasks")] Task<ApiResponse<CreateCollectionTaskResponse>> CreateCollectionTaskAsync([Body] CreateCollectionTaskRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/known-recovery-batches")] Task<ApiResponse<CreateKnownRecoveryBatchResponse>> CreateKnownRecoveryBatchAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/race-entry-owner-repair-batches")] Task<ApiResponse<CreateRaceEntryOwnerRepairBatchResponse>> CreateRaceEntryOwnerRepairBatchAsync([Body] CreateRaceEntryOwnerRepairBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recollection-batches")] Task<ApiResponse<CreateRecollectionBatchResponse>> CreateRecollectionBatchAsync([Body] CreateRecollectionBatchRequest request, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/backfill-batches/{id}")] Task<ApiResponse<GetBackfillBatchResponse>> GetBackfillBatchAsync([AliasAs("id")] string id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/dashboard")] Task<ApiResponse<GetCollectionDashboardResponse>> GetCollectionDashboardAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/monitoring-findings")] Task<ApiResponse<GetCollectionMonitoringFindingsResponse>> GetCollectionMonitoringFindingsAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/pipeline-state")] Task<ApiResponse<GetCollectionPipelineResponse>> GetCollectionPipelineAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/progress")] Task<ApiResponse<GetCollectionProgressResponse>> GetCollectionProgressAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/resources/{type}/{provider}/{resourceId}/definitions/{definition}")] Task<ApiResponse<GetCollectionResourceDetailResponse>> GetCollectionResourceDetailAsync([AliasAs("type")] CollectionResourceType type, [AliasAs("provider")] string provider, [AliasAs("resourceId")] string resourceId, [AliasAs("definition")] string definition, [AliasAs("historyPage")] int? historyPage, [AliasAs("requestHistoryPage")] int? requestHistoryPage, [AliasAs("taskHistoryPage")] int? taskHistoryPage, [AliasAs("attemptHistoryPage")] int? attemptHistoryPage, [AliasAs("historyPageSize")] int? historyPageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/resources/{type}/{provider}/{resourceId}/definitions/{definition}/state")] Task<ApiResponse<GetCollectionResourceStateResponse>> GetCollectionResourceStateAsync([AliasAs("type")] CollectionResourceType type, [AliasAs("provider")] string provider, [AliasAs("resourceId")] string resourceId, [AliasAs("definition")] string definition, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/execution-batches/{id}")] Task<ApiResponse<GetExecutionBatchResponse>> GetExecutionBatchAsync([AliasAs("id")] Guid id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notification-groups/{groupKey}")] Task<ApiResponse<GetFailureNotificationGroupResponse>> GetFailureNotificationGroupAsync([AliasAs("groupKey")] string groupKey, [AliasAs("search")] string? search, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/recovery-previews/known")] Task<ApiResponse<GetKnownRecoveryPreviewResponse>> GetKnownRecoveryPreviewAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/migration-previews/owner-identity")] Task<ApiResponse<GetOwnerIdentityMigrationPreviewResponse>> GetOwnerIdentityMigrationPreviewAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/races/{raceId}/readiness")] Task<ApiResponse<GetRaceCollectionReadinessResponse>> GetRaceCollectionReadinessAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/migrations/race-entry-owner-repair")] Task<ApiResponse<GetRaceEntryOwnerMigrationResponse>> GetRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/recollection-batches")] Task<ApiResponse<GetRevisionRecollectionProgressResponse>> GetRevisionRecollectionProgressAsync([AliasAs("definition")] string definition, [AliasAs("revision")] int revision, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/operations/task-view-counts")] Task<ApiResponse<GetTaskViewCountsResponse>> GetTaskViewCountsAsync(CancellationToken cancellationToken);
    [Patch("/api/v2/internal/collection/tasks/{id}/leases/{leaseId}")] Task<ApiResponse<HeartbeatCollectionTaskLeaseResponse>> HeartbeatCollectionTaskLeaseAsync([AliasAs("id")] Guid id, [AliasAs("leaseId")] string leaseId, [Body] HeartbeatCollectionTaskLeaseRequest request, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/backfill-batches")] Task<ApiResponse<ListBackfillBatchesResponse>> ListBackfillBatchesAsync(CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/tasks")] Task<ApiResponse<ListCollectionTasksResponse>> ListCollectionTasksAsync([AliasAs("status")] CollectionTaskStatus? status, [AliasAs("limit")] int? limit, [AliasAs("statuses")] string? statuses, [AliasAs("resourceType")] CollectionResourceType? resourceType, [AliasAs("provider")] string? provider, [AliasAs("definitionId")] string? definitionId, [AliasAs("lane")] CollectionLane? lane, [AliasAs("search")] string? search, [AliasAs("errorSearch")] string? errorSearch, [AliasAs("createdFrom")] DateTimeOffset? createdFrom, [AliasAs("createdTo")] DateTimeOffset? createdTo, [AliasAs("actionableOnly")] bool? actionableOnly, [AliasAs("latestOnly")] bool? latestOnly, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notification-groups")] Task<ApiResponse<ListFailureNotificationGroupsResponse>> ListFailureNotificationGroupsAsync([AliasAs("limit")] int? limit, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/failure-notifications")] Task<ApiResponse<ListFailureNotificationsResponse>> ListFailureNotificationsAsync([AliasAs("view")] string? view, [AliasAs("published")] bool? published, [AliasAs("deliveryState")] string? deliveryState, [AliasAs("limit")] int? limit, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/race-entry-owner-repair-candidates")] Task<ApiResponse<ListRaceEntryOwnerRepairCandidatesResponse>> ListRaceEntryOwnerRepairCandidatesAsync([AliasAs("date")] DateOnly date, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/task-batch-previews")] Task<ApiResponse<PreviewCollectionTaskBatchResponse>> PreviewCollectionTaskBatchAsync([Body] PreviewCollectionTaskBatchRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migration-previews/race-detail")] Task<ApiResponse<PreviewRaceDetailMigrationResponse>> PreviewRaceDetailMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/migration-previews/race-entry-owner-repair")] Task<ApiResponse<PreviewRaceEntryOwnerMigrationResponse>> PreviewRaceEntryOwnerMigrationAsync(CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/recollection-previews")] Task<ApiResponse<PreviewRacePeriodRecollectionResponse>> PreviewRacePeriodRecollectionAsync([Body] PreviewRacePeriodRecollectionRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/revision-impact-previews")] Task<ApiResponse<PreviewRevisionImpactResponse>> PreviewRevisionImpactAsync([Body] PreviewRevisionImpactRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/collection/backfill-batches/{id}/recovery-batches")] Task<ApiResponse<RecoverBackfillHolesResponse>> RecoverBackfillHolesAsync([AliasAs("id")] string id, CancellationToken cancellationToken);
    [Get("/api/v2/admin/collection/states")] Task<ApiResponse<SearchCollectionStatesResponse>> SearchCollectionStatesAsync([AliasAs("statuses")] string? statuses, [AliasAs("resourceType")] CollectionResourceType? resourceType, [AliasAs("provider")] string? provider, [AliasAs("definitionId")] string? definitionId, [AliasAs("search")] string? search, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, CancellationToken cancellationToken);
    [Put("/api/v2/admin/collection/pipeline")] Task<IApiResponse> SetCollectionPipelineAsync([Body] SetCollectionPipelineRequest request, CancellationToken cancellationToken);
    [Patch("/api/v2/internal/collection/execution-batches/{id}")] Task<IApiResponse> TransitionCollectionExecutionAsync([AliasAs("id")] Guid id, [Body] TransitionCollectionExecutionRequest request, CancellationToken cancellationToken);
}
