using HorseRacingPrediction.Contracts.Collection;
using HorseRacingPrediction.Contracts.Common.Time;
using HorseRacingPrediction.Contracts.Horses;
using HorseRacingPrediction.Contracts.Identity;
using HorseRacingPrediction.Contracts.Jockeys;
using HorseRacingPrediction.Contracts.MachineLearning;
using HorseRacingPrediction.Contracts.Memos;
using HorseRacingPrediction.Contracts.Owners;
using HorseRacingPrediction.Contracts.Predictions;
using HorseRacingPrediction.Contracts.PredictionScheduling;
using HorseRacingPrediction.Contracts.Races;
using HorseRacingPrediction.Contracts.Repairs;
using HorseRacingPrediction.Contracts.Subjects;
using HorseRacingPrediction.Contracts.Trainers;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HorseRacingPrediction.ApiClient;

[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, Converters = new[] { typeof(JstDateTimeOffsetJsonConverter), typeof(NumericRequestFlexibleResponseEnumConverterFactory) })]
[JsonSerializable(typeof(AcquireCollectionTaskRequest))]
[JsonSerializable(typeof(AcquireCollectionTaskResponse))]
[JsonSerializable(typeof(AcquireNextExecutionRequest))]
[JsonSerializable(typeof(AcquireNextExecutionResponse))]
[JsonSerializable(typeof(ApplyRaceDetailMigrationResponse))]
[JsonSerializable(typeof(ApplyRaceEntryOwnerMigrationResponse))]
[JsonSerializable(typeof(CancelCollectionTaskRequest))]
[JsonSerializable(typeof(CompleteCollectionTaskAttemptRequest))]
[JsonSerializable(typeof(CreateBackfillBatchRequest))]
[JsonSerializable(typeof(CreateBackfillBatchResponse))]
[JsonSerializable(typeof(CreateCollectionRecoveryBatchRequest))]
[JsonSerializable(typeof(CreateCollectionRecoveryBatchResponse))]
[JsonSerializable(typeof(CreateCollectionRevisionRequest))]
[JsonSerializable(typeof(CreateCollectionRevisionResponse))]
[JsonSerializable(typeof(CreateCollectionTaskBatchRequest))]
[JsonSerializable(typeof(CreateCollectionTaskBatchResponse))]
[JsonSerializable(typeof(CreateCollectionTaskRequest))]
[JsonSerializable(typeof(CreateCollectionTaskResponse))]
[JsonSerializable(typeof(CreateKnownRecoveryBatchResponse))]
[JsonSerializable(typeof(CreateRaceEntryOwnerRepairBatchRequest))]
[JsonSerializable(typeof(CreateRaceEntryOwnerRepairBatchResponse))]
[JsonSerializable(typeof(CreateRecollectionBatchRequest))]
[JsonSerializable(typeof(CreateRecollectionBatchResponse))]
[JsonSerializable(typeof(GetBackfillBatchRequest))]
[JsonSerializable(typeof(GetBackfillBatchResponse))]
[JsonSerializable(typeof(GetCollectionDashboardResponse))]
[JsonSerializable(typeof(GetCollectionMonitoringFindingsResponse))]
[JsonSerializable(typeof(GetCollectionPipelineResponse))]
[JsonSerializable(typeof(GetCollectionProgressResponse))]
[JsonSerializable(typeof(GetCollectionResourceDetailRequest))]
[JsonSerializable(typeof(GetCollectionResourceDetailResponse))]
[JsonSerializable(typeof(GetCollectionResourceStateRequest))]
[JsonSerializable(typeof(GetCollectionResourceStateResponse))]
[JsonSerializable(typeof(GetExecutionBatchRequest))]
[JsonSerializable(typeof(GetExecutionBatchResponse))]
[JsonSerializable(typeof(GetFailureNotificationGroupRequest))]
[JsonSerializable(typeof(GetFailureNotificationGroupResponse))]
[JsonSerializable(typeof(GetKnownRecoveryPreviewResponse))]
[JsonSerializable(typeof(GetOwnerIdentityMigrationPreviewResponse))]
[JsonSerializable(typeof(GetRaceCollectionReadinessRequest))]
[JsonSerializable(typeof(GetRaceCollectionReadinessResponse))]
[JsonSerializable(typeof(GetRaceEntryOwnerMigrationResponse))]
[JsonSerializable(typeof(GetRevisionRecollectionProgressRequest))]
[JsonSerializable(typeof(GetRevisionRecollectionProgressResponse))]
[JsonSerializable(typeof(GetTaskViewCountsResponse))]
[JsonSerializable(typeof(HeartbeatCollectionTaskLeaseRequest))]
[JsonSerializable(typeof(HeartbeatCollectionTaskLeaseResponse))]
[JsonSerializable(typeof(ListBackfillBatchesResponse))]
[JsonSerializable(typeof(ListCollectionTasksRequest))]
[JsonSerializable(typeof(ListCollectionTasksResponse))]
[JsonSerializable(typeof(ListFailureNotificationGroupsRequest))]
[JsonSerializable(typeof(ListFailureNotificationGroupsResponse))]
[JsonSerializable(typeof(ListFailureNotificationsRequest))]
[JsonSerializable(typeof(ListFailureNotificationsResponse))]
[JsonSerializable(typeof(ListRaceEntryOwnerRepairCandidatesRequest))]
[JsonSerializable(typeof(ListRaceEntryOwnerRepairCandidatesResponse))]
[JsonSerializable(typeof(PreviewCollectionTaskBatchRequest))]
[JsonSerializable(typeof(PreviewCollectionTaskBatchResponse))]
[JsonSerializable(typeof(PreviewRaceDetailMigrationResponse))]
[JsonSerializable(typeof(PreviewRaceEntryOwnerMigrationResponse))]
[JsonSerializable(typeof(PreviewRacePeriodRecollectionRequest))]
[JsonSerializable(typeof(PreviewRacePeriodRecollectionResponse))]
[JsonSerializable(typeof(PreviewRevisionImpactRequest))]
[JsonSerializable(typeof(PreviewRevisionImpactResponse))]
[JsonSerializable(typeof(RecoverBackfillHolesRequest))]
[JsonSerializable(typeof(RecoverBackfillHolesResponse))]
[JsonSerializable(typeof(SearchCollectionStatesRequest))]
[JsonSerializable(typeof(SearchCollectionStatesResponse))]
[JsonSerializable(typeof(SetCollectionPipelineRequest))]
[JsonSerializable(typeof(TransitionCollectionExecutionRequest))]
[JsonSerializable(typeof(CorrectHorseDataRequest))]
[JsonSerializable(typeof(GetHorseParticipationsRequest))]
[JsonSerializable(typeof(GetHorseParticipationsResponse))]
[JsonSerializable(typeof(GetHorseProfileRequest))]
[JsonSerializable(typeof(GetHorseProfileResponse))]
[JsonSerializable(typeof(GetHorseRaceHistoryRequest))]
[JsonSerializable(typeof(GetHorseRaceHistoryResponse))]
[JsonSerializable(typeof(GetHorseWeightHistoryRequest))]
[JsonSerializable(typeof(GetHorseWeightHistoryResponse))]
[JsonSerializable(typeof(MergeHorseAliasRequest))]
[JsonSerializable(typeof(RegisterHorseRequest))]
[JsonSerializable(typeof(RegisterHorseResponse))]
[JsonSerializable(typeof(SearchHorsesRequest))]
[JsonSerializable(typeof(SearchHorsesResponse))]
[JsonSerializable(typeof(UpdateHorseProfileRequest))]
[JsonSerializable(typeof(ResolveHorseIdentityRequest))]
[JsonSerializable(typeof(ResolveHorseIdentityResponse))]
[JsonSerializable(typeof(ResolveRaceIdentityRequest))]
[JsonSerializable(typeof(ResolveRaceIdentityResponse))]
[JsonSerializable(typeof(CorrectJockeyDataRequest))]
[JsonSerializable(typeof(GetJockeyParticipationsRequest))]
[JsonSerializable(typeof(GetJockeyParticipationsResponse))]
[JsonSerializable(typeof(GetJockeyProfileRequest))]
[JsonSerializable(typeof(GetJockeyProfileResponse))]
[JsonSerializable(typeof(GetJockeyRaceHistoryRequest))]
[JsonSerializable(typeof(GetJockeyRaceHistoryResponse))]
[JsonSerializable(typeof(MergeJockeyAliasRequest))]
[JsonSerializable(typeof(RegisterJockeyRequest))]
[JsonSerializable(typeof(RegisterJockeyResponse))]
[JsonSerializable(typeof(SearchJockeysRequest))]
[JsonSerializable(typeof(SearchJockeysResponse))]
[JsonSerializable(typeof(UpdateJockeyProfileRequest))]
[JsonSerializable(typeof(GetMlPredictionRequest))]
[JsonSerializable(typeof(GetMlPredictionResponse))]
[JsonSerializable(typeof(TrainMlModelResponse))]
[JsonSerializable(typeof(ChangeMemoSubjectsRequest))]
[JsonSerializable(typeof(CreateMemoRequest))]
[JsonSerializable(typeof(CreateMemoResponse))]
[JsonSerializable(typeof(DeleteMemoRequest))]
[JsonSerializable(typeof(GetMemosBySubjectRequest))]
[JsonSerializable(typeof(GetMemosBySubjectResponse))]
[JsonSerializable(typeof(UpdateMemoRequest))]
[JsonSerializable(typeof(ExecuteOwnerIdentityRecoveryRequest))]
[JsonSerializable(typeof(ExecuteOwnerIdentityRecoveryResponse))]
[JsonSerializable(typeof(GetOwnerRequest))]
[JsonSerializable(typeof(GetOwnerResponse))]
[JsonSerializable(typeof(MergeOwnerRequest))]
[JsonSerializable(typeof(PreviewOwnerIdentityRecoveryResponse))]
[JsonSerializable(typeof(SearchOwnersRequest))]
[JsonSerializable(typeof(SearchOwnersResponse))]
[JsonSerializable(typeof(UpdateOwnerRequest))]
[JsonSerializable(typeof(AcquirePredictionCandidateLeasesRequest))]
[JsonSerializable(typeof(AcquirePredictionCandidateLeasesResponse))]
[JsonSerializable(typeof(EnqueuePredictionCandidatesRequest))]
[JsonSerializable(typeof(TransitionPredictionCandidateRequest))]
[JsonSerializable(typeof(AddBettingSuggestionRequest))]
[JsonSerializable(typeof(AddPredictionMarkRequest))]
[JsonSerializable(typeof(AddPredictionRationaleRequest))]
[JsonSerializable(typeof(CorrectPredictionMetadataRequest))]
[JsonSerializable(typeof(CreatePredictionTicketRequest))]
[JsonSerializable(typeof(CreatePredictionTicketResponse))]
[JsonSerializable(typeof(EvaluatePredictionTicketRequest))]
[JsonSerializable(typeof(FinalizePredictionTicketRequest))]
[JsonSerializable(typeof(GetPredictionTicketRequest))]
[JsonSerializable(typeof(GetPredictionTicketResponse))]
[JsonSerializable(typeof(RecalculatePredictionEvaluationRequest))]
[JsonSerializable(typeof(SearchPredictionTicketsRequest))]
[JsonSerializable(typeof(SearchPredictionTicketsResponse))]
[JsonSerializable(typeof(WithdrawPredictionTicketRequest))]
[JsonSerializable(typeof(ApplyRaceEntryRepairRequest))]
[JsonSerializable(typeof(ApplyRaceEntryRepairResponse))]
[JsonSerializable(typeof(CloseRaceLifecycleRequest))]
[JsonSerializable(typeof(CorrectRaceDataRequest))]
[JsonSerializable(typeof(CreateRaceFromScheduleRequest))]
[JsonSerializable(typeof(CreateRaceFromScheduleResponse))]
[JsonSerializable(typeof(CreateRaceOddsSnapshotRequest))]
[JsonSerializable(typeof(CreateRaceRequest))]
[JsonSerializable(typeof(CreateRaceResponse))]
[JsonSerializable(typeof(DeclareEntryResultRequest))]
[JsonSerializable(typeof(DeclarePayoutResultRequest))]
[JsonSerializable(typeof(DeclareRaceResultBulkRequest))]
[JsonSerializable(typeof(DeclareRaceResultBulkResponse))]
[JsonSerializable(typeof(DeclareRaceResultRequest))]
[JsonSerializable(typeof(GetPredictionComparisonRequest))]
[JsonSerializable(typeof(GetPredictionComparisonResponse))]
[JsonSerializable(typeof(GetRaceAssignmentFenceRequest))]
[JsonSerializable(typeof(GetRaceAssignmentFenceResponse))]
[JsonSerializable(typeof(GetRaceEntryRepairHoldRequest))]
[JsonSerializable(typeof(GetRaceEntryRepairHoldResponse))]
[JsonSerializable(typeof(GetRaceEntryRepairRequest))]
[JsonSerializable(typeof(GetRaceEntryRepairResponse))]
[JsonSerializable(typeof(GetRacePredictionContextRequest))]
[JsonSerializable(typeof(GetRacePredictionContextResponse))]
[JsonSerializable(typeof(GetRaceRequest))]
[JsonSerializable(typeof(GetRaceResponse))]
[JsonSerializable(typeof(ListRaceOddsSnapshotsRequest))]
[JsonSerializable(typeof(ListRaceOddsSnapshotsResponse))]
[JsonSerializable(typeof(MarkRaceRescheduledRequest))]
[JsonSerializable(typeof(OpenPreRaceRequest))]
[JsonSerializable(typeof(PreviewRaceEntryRepairRequest))]
[JsonSerializable(typeof(PreviewRaceEntryRepairResponse))]
[JsonSerializable(typeof(PublishRaceCardRequest))]
[JsonSerializable(typeof(RecordTrackConditionRequest))]
[JsonSerializable(typeof(RecordWeatherObservationRequest))]
[JsonSerializable(typeof(RegisterEntryRequest))]
[JsonSerializable(typeof(RegisterEntryResponse))]
[JsonSerializable(typeof(ReleaseRaceEntryRepairHoldRequest))]
[JsonSerializable(typeof(ReleaseRaceEntryRepairHoldResponse))]
[JsonSerializable(typeof(SearchRacesRequest))]
[JsonSerializable(typeof(SearchRacesResponse))]
[JsonSerializable(typeof(StartRaceRequest))]
[JsonSerializable(typeof(UpdateEntryCollectedDataRequest))]
[JsonSerializable(typeof(UpdateEntryCollectedDataResponse))]
[JsonSerializable(typeof(UpdateRaceEntryRepairHoldRequest))]
[JsonSerializable(typeof(UpdateRaceEntryRepairHoldResponse))]
[JsonSerializable(typeof(ApplyHorseIdentityRepairRequest))]
[JsonSerializable(typeof(ApplyHorseIdentityRepairResponse))]
[JsonSerializable(typeof(ApplySubjectNameNormalizationRequest))]
[JsonSerializable(typeof(ApplySubjectNameNormalizationResponse))]
[JsonSerializable(typeof(DismissSubjectIdentificationFailuresRequest))]
[JsonSerializable(typeof(DismissSubjectIdentificationFailuresResponse))]
[JsonSerializable(typeof(ExecuteSubjectIdentificationRepairRequest))]
[JsonSerializable(typeof(ExecuteSubjectIdentificationRepairResponse))]
[JsonSerializable(typeof(GetHorseIdentityRepairResponse))]
[JsonSerializable(typeof(GetSubjectIdentificationRepairResponse))]
[JsonSerializable(typeof(GetSubjectNameNormalizationRequest))]
[JsonSerializable(typeof(GetSubjectNameNormalizationResponse))]
[JsonSerializable(typeof(GetSubjectProfileRequest))]
[JsonSerializable(typeof(GetSubjectProfileResponse))]
[JsonSerializable(typeof(PutSubjectProfileRequest))]
[JsonSerializable(typeof(CorrectTrainerDataRequest))]
[JsonSerializable(typeof(GetTrainerParticipationsRequest))]
[JsonSerializable(typeof(GetTrainerParticipationsResponse))]
[JsonSerializable(typeof(GetTrainerProfileRequest))]
[JsonSerializable(typeof(GetTrainerProfileResponse))]
[JsonSerializable(typeof(MergeTrainerAliasRequest))]
[JsonSerializable(typeof(RegisterTrainerRequest))]
[JsonSerializable(typeof(RegisterTrainerResponse))]
[JsonSerializable(typeof(SearchTrainersRequest))]
[JsonSerializable(typeof(SearchTrainersResponse))]
[JsonSerializable(typeof(UpdateTrainerProfileRequest))]
internal partial class ApiClientJsonContext : JsonSerializerContext
{
    internal static JsonSerializerOptions CreateOptions()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        options.TypeInfoResolver = Default;
        options.Converters.Add(new JstDateTimeOffsetJsonConverter());
        options.Converters.Add(new NumericRequestFlexibleResponseEnumConverterFactory());
        return options;
    }
}
