namespace HorseRacingPrediction.Api.Contracts;

public sealed record RaceResponse(
    string RaceId,
    DateOnly? RaceDate,
    string? RacecourseCode,
    int? RaceNumber,
    string? RaceName,
    RaceStatus Status,
    int? MeetingNumber,
    int? DayNumber,
    string? GradeCode,
    string? SurfaceCode,
    int? DistanceMeters,
    string? DirectionCode,
    int? EntryCount,
    IReadOnlyList<RaceEntryResponse> Entries,
    IReadOnlyList<RaceWeatherObservationResponse> WeatherObservations,
    IReadOnlyList<RaceTrackConditionResponse> TrackConditionObservations,
    RaceOddsResponse? Odds,
    string? WinningHorseName,
    string? WinningHorseId,
    string? StewardReportText,
    DateTimeOffset? ResultDeclaredAt,
    IReadOnlyList<RaceEntryResultResponse> EntryResults,
    RacePayoutResultResponse? PayoutResult);
