using Refit;
using HorseRacingPrediction.Contracts.Races;

namespace HorseRacingPrediction.ApiClient.Races;

internal interface IRacesTransport
{
    [Post("/api/v2/admin/races/{raceId}/entry-repairs")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.ApplyRaceEntryRepairResponse>> ApplyRaceEntryRepairAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.ApplyRaceEntryRepairRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/close")] Task<IApiResponse> CloseRaceLifecycleAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Patch("/api/races/{raceId}")] Task<IApiResponse> CorrectRaceDataAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.CorrectRaceDataRequest request, CancellationToken cancellationToken);
    [Post("/api/races")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.CreateRaceResponse>> CreateRaceAsync([Body] global::HorseRacingPrediction.Contracts.Races.CreateRaceRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/races")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.CreateRaceFromScheduleResponse>> CreateRaceFromScheduleAsync([Body] global::HorseRacingPrediction.Contracts.Races.CreateRaceFromScheduleRequest request, CancellationToken cancellationToken);
    [Post("/api/v2/admin/races/{raceId}/odds-snapshot-records")] Task<IApiResponse> CreateRaceOddsSnapshotAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.CreateRaceOddsSnapshotRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/entries/{entryId}/result")] Task<IApiResponse> DeclareEntryResultAsync([AliasAs("raceId")] string raceId, [AliasAs("entryId")] string entryId, [Body] global::HorseRacingPrediction.Contracts.Races.DeclareEntryResultRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/payout")] Task<IApiResponse> DeclarePayoutResultAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.DeclarePayoutResultRequest request, CancellationToken cancellationToken);
    [Post("/api/races/result-bulk")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.DeclareRaceResultBulkResponse>> DeclareRaceResultBulkAsync([Body] global::HorseRacingPrediction.Contracts.Races.DeclareRaceResultBulkRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/result")] Task<IApiResponse> DeclareRaceResultAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.DeclareRaceResultRequest request, CancellationToken cancellationToken);
    [Get("/api/races/{raceId}/comparison")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetPredictionComparisonResponse>> GetPredictionComparisonAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/races/{raceId}/entry-repair/assignment-fence-state")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetRaceAssignmentFenceResponse>> GetRaceAssignmentFenceAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/races/{raceId}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetRaceResponse>> GetRaceAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/races/{raceId}/entry-repair/inspection")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetRaceEntryRepairResponse>> GetRaceEntryRepairAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/races/{raceId}/entry-repair/hold-state")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetRaceEntryRepairHoldResponse>> GetRaceEntryRepairHoldAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/races/{raceId}/context")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.GetRacePredictionContextResponse>> GetRacePredictionContextAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Get("/api/v2/admin/races/{raceId}/odds-snapshot-records")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.ListRaceOddsSnapshotsResponse>> ListRaceOddsSnapshotsAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/reschedule")] Task<IApiResponse> MarkRaceRescheduledAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.MarkRaceRescheduledRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/open-pre-race")] Task<IApiResponse> OpenPreRaceAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Post("/api/v2/admin/races/{raceId}/entry-repair-previews")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.PreviewRaceEntryRepairResponse>> PreviewRaceEntryRepairAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.PreviewRaceEntryRepairRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/card/publish")] Task<IApiResponse> PublishRaceCardAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.PublishRaceCardRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/track-condition")] Task<IApiResponse> RecordTrackConditionAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.RecordTrackConditionRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/weather")] Task<IApiResponse> RecordWeatherObservationAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.RecordWeatherObservationRequest request, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/entries")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.RegisterEntryResponse>> RegisterEntryAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.RegisterEntryRequest request, CancellationToken cancellationToken);
    [Patch("/api/v2/admin/races/{raceId}/entry-repair/hold")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.ReleaseRaceEntryRepairHoldResponse>> ReleaseRaceEntryRepairHoldAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.ReleaseRaceEntryRepairHoldRequest request, CancellationToken cancellationToken);
    [Get("/api/races")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.SearchRacesResponse>> SearchRacesAsync([AliasAs("raceId")] string? raceId, [AliasAs("raceDateFrom")] DateOnly? raceDateFrom, [AliasAs("raceDateTo")] DateOnly? raceDateTo, [AliasAs("racecourseCode")] string? racecourseCode, [AliasAs("raceNumber")] int? raceNumber, [AliasAs("raceName")] string? raceName, [AliasAs("status")] global::HorseRacingPrediction.Contracts.Races.RaceStatus? status, [AliasAs("winningHorseName")] string? winningHorseName, [AliasAs("page")] int? page, [AliasAs("pageSize")] int? pageSize, [AliasAs("sortBy")] string? sortBy, [AliasAs("sortDescending")] bool? sortDescending, CancellationToken cancellationToken);
    [Post("/api/races/{raceId}/start")] Task<IApiResponse> StartRaceAsync([AliasAs("raceId")] string raceId, CancellationToken cancellationToken);
    [Put("/api/races/{raceId}/entries/{entryId}")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.UpdateEntryCollectedDataResponse>> UpdateEntryCollectedDataAsync([AliasAs("raceId")] string raceId, [AliasAs("entryId")] string entryId, [Body] global::HorseRacingPrediction.Contracts.Races.UpdateEntryCollectedDataRequest request, CancellationToken cancellationToken);
    [Put("/api/v2/admin/races/{raceId}/entry-repair/hold")] Task<ApiResponse<global::HorseRacingPrediction.Contracts.Races.UpdateRaceEntryRepairHoldResponse>> UpdateRaceEntryRepairHoldAsync([AliasAs("raceId")] string raceId, [Body] global::HorseRacingPrediction.Contracts.Races.UpdateRaceEntryRepairHoldRequest request, CancellationToken cancellationToken);
}
